### ISSUE TITLE
Store stats in table 

### ISSUE THREAD

**Issue by eric-haibin-lin** [eric-haibin-lin/peloton-1#1]
Currently statistics are stored in the `aggregator` object. Moving the stat to a database table makes it easier to manage these data, with the existing functionality peloton supports.  

I am going to:
- On `Catalog` initialization, create three tables in the catalog database, for `DatabaseMetrics`, `TableMetrics` and `IndexMetrics`. Attributes of these class are mapped to the columns of the database table. 
- In each aggregation run, insert new aggregation results as tuples to the tables. 

@malin1993ml

**Comment by linmagit** [comment]
Looks good to me!
