### ISSUE TITLE
Per Query Stat

### ISSUE THREAD

**Issue by eric-haibin-lin** [eric-haibin-lin/peloton-1#2]
Recording per query stat:

`QueryMetric` records the number of tuples accessed by a query. 

In BackendContext, add two member variables:
shared_ptr<QueryMetric> `on_going_query_metric`, which records stat of the on going query 
LockFreeQueue<shared_ptr<QueryMetric>> `completed_query_stat`, which stores queries completed. 

When a query commits or aborts, move the `on_going_query_metric` to the queue.

The aggregator thread polls query metric from the queue periodically. 

@malin1993ml

**Comment by linmagit** [comment]
Can we make on_going_query_metric a unique_ptr? We should make the onwership clear and avoid shared_ptr if possible.

**Comment by eric-haibin-lin** [comment]
That's a good point, however, I don't think we can put a unique ptr in the queue..

**Comment by linmagit** [comment]
Okay. That's fine.
