### ISSUE TITLE
Just my own question

### ISSUE THREAD

**Issue by pzz2011** [eric-haibin-lin/peloton-1#4]
I have passed the compiling  process.
But I still wonder that if I do not execute the .sh `script/installation/packages.sh`, why the cmake report
undefine pthred_xxxx error.

I have little experience over cmake. Hope u can answer my question and give me some advice, thanks . 

#

**Comment by eric-haibin-lin** [comment]
Peloton uses c++ 11. I believe packages.sh installs most recent version of g++ and cmake. You can compile once you have all dependency ready. 

In general I encourage you to post issues on cmu-db/peloton, where issues are actively monitored.

**Comment by pzz2011** [comment]
@eric-haibin-lin  Ok, I will. And indeed, I am very scare to C++ template program.
while peloton has a lot of template code including the thrid-part library....
I hope I can learn some experience from you. I'm serious:)
